services:
  - type: web
    name: server
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    envVars:
      - key: PG_DATABASE_URL
        value: postgres://twenty:twenty@twenty-postgres:5432/default?connection_limit=1  